-keep class com.gmwalkaround.inspection.** { *; }
-keep interface com.gmwalkaround.inspection.** { *; }
-keep class retrofit2.** { *; }
-keep interface retrofit2.** { *; }
-keepattributes Signature
-keepattributes Exceptions
